### ISSUE TITLE
Adding 6 unique dishes

### ISSUE THREAD

**Issue by bhavkushwaha** [TheGuyDangerous/FoodCoders#110]
I would like to add 6 more unique dishes in the website. 
(Participating in the TRC - Winter of Code)
I have checked all the webpages in the recipe section and chosen 6 unique dishes to add. Will be strictly following the procedure described in the document in order to make a contribution smoothly.
6 Dishes that I will be adding are:
1. Kadi Chawal
2. Chow mein
3. Gajar Ka Halwa
4. Tomato Soup
5. Sushi
6. Kheer

**Comment by TheGuyDangerous** [comment]
Go ahead ! @bhavkushwaha 

Make sure to star the repository while you're at it  ✨
