### ISSUE TITLE
Add 6 New Recipes

### ISSUE THREAD

**Issue by NisharN** [TheGuyDangerous/FoodCoders#112]
Adding new recipes page

**Comment by TheGuyDangerous** [comment]
Please refer to #110 , and add your details similar to this issue.
Do keep in my to adhere with the contributing guidelines, else your pr would be rejected.

**Comment by TheGuyDangerous** [comment]
@NisharN updates ?

(If no updates are provided within the next 24hrs. , then this issue will be closed automatically.)

**Comment by sawood164** [comment]
can i take up this issue ?
