### ISSUE TITLE
Fix Image Quality Issue across the Website

### ISSUE THREAD

**Issue by TheGuyDangerous** [TheGuyDangerous/FoodCoders#114]
**Describe the issue**

Convert every image - up until, Page 13 to
 - A transparent ```png``` version of the image.
 - A folder name consisting of the page number, along with the new ```png format``` transparent images for the dishes.
 - Convert the image size to under 500kb, with no hit to image resolution.

**Comment by bhavkushwaha** [comment]
@TheGuyDangerous I will like to work on this enhancement feature. Please assign this issue to me.

**Comment by TheGuyDangerous** [comment]
Go ahead ! @bhavkushwaha

**Comment by bhavkushwaha** [comment]
@TheGuyDangerous I have started the process of converting the already stored images into transparent ones. But some images are of a bit lower quality and upon converting them into png the quality further degrades.
Also when removing the background of some images the main portion is actually not fully in the image so the image after removing the background appears to be cut.

My Solution: The images which do not degrade upon removing the background and converting to png should be kept, and those which have problems should be changed by the better ones.
The below example doesn't look good, so I recomend you to allow me to upload new images which are suitable and appear good after removing the background wherever necessary.

Problem Example Shown Below:

Before: Image with a background
![bhel-puri](https://github.com/TheGuyDangerous/FoodCoders/assets/75977991/d9a3483d-29f6-4f1b-97a0-6f9a73f95928) 

After: Image after removing the background
![bhel-puri-min](https://github.com/TheGuyDangerous/FoodCoders/assets/75977991/5feebb2c-1f3e-4eb2-96ed-acd41caa2ca8)

**Comment by TheGuyDangerous** [comment]
Hi @bhavkushwaha , You can add alternate images instead, with proper plate cutouts, instead of half plate images.

**Comment by bhavkushwaha** [comment]
Okay Thanks @TheGuyDangerous ,I am proceeding to update the Images Folder and the corresponding code of the webpages.

**Comment by bhavkushwaha** [comment]
@TheGuyDangerous I have created all the required folders and populated them with the transparent PNG images of all the food item. It was a long process but I hope it is good enough.
