### ISSUE TITLE
Smooth hover effect on the recipe images

### ISSUE THREAD

**Issue by SSShogunn** [TheGuyDangerous/FoodCoders#115]
Previous hover effect:
https://github.com/TheGuyDangerous/FoodCoders/assets/100095370/b180eab1-1f1e-4925-90db-2789c9b3e001

After hover effect:
https://github.com/TheGuyDangerous/FoodCoders/assets/100095370/9173a6b4-ae1d-4750-af92-2ce5758af122

**Comment by TheGuyDangerous** [comment]
Go ahead 😃 @SSShogunn !!

Make sure to star the repo while you're at it ✨
