### ISSUE TITLE
Navigation Bar 

### ISSUE THREAD

**Issue by pragathish07** [TheGuyDangerous/FoodCoders#118]
when I go to the about page, or Contact page there is a different navbar, I can add the same navbar throughout the page
this is in home page
![Screenshot (4)](https://github.com/TheGuyDangerous/FoodCoders/assets/91775771/203cf13f-79de-4d85-bf3e-46a2b2ad798d)

this is in the about page 

![Screenshot (3)](https://github.com/TheGuyDangerous/FoodCoders/assets/91775771/07e24e3e-9dd4-4b4a-aada-d3a7543b3cbe)

I can add the same navbar throughout all the pages. @TheGuyDangerous

**Comment by TheGuyDangerous** [comment]
Yes, That would be very helpful of you ! @pragathish07 

I've assigned you the issue.
Make sure to also add it to all the pages..

**Comment by TheGuyDangerous** [comment]
@pragathish07 updates on the changes requested ?

**Comment by TheGuyDangerous** [comment]
> @pragathish07 updates on the changes requested ?

.

**Comment by Priyanshuraj21030** [comment]
Can I work on this issue?

**Comment by TheGuyDangerous** [comment]
> Can I work on this issue?

Go ahead !
