### ISSUE TITLE
Add 6 more unique recipes

### ISSUE THREAD

**Issue by Monika5S** [TheGuyDangerous/FoodCoders#120]
I would like to add 6 more unique recipes in the website. (participant of TRC-Winter of Code)

I have checked all the webpages in the recipe section and chosen 6 unique recipes to add. Will be strictly following the procedure described in the document in order to make a contribution smoothly.

6 recipes that I will be adding are:
1. Khandvi
2. Lemon rice
3. Hot chocolate
4. Iced coffee
5. Soya Malai Chaap
6. Uttapam

**Comment by TheGuyDangerous** [comment]
Hi @Monika5S , do the changes requested, before it finally gets merged.
