### ISSUE TITLE
Create new pages for new recipes 

### ISSUE THREAD

**Issue by TheGuyDangerous** [TheGuyDangerous/FoodCoders#18]
Create new pages , Linking to new recipes. You are allowed to use the website's previous pages as a template to create new pages.

**Comment by SamagraAg** [comment]
@TheGuyDangerous assign it to me

**Comment by TheGuyDangerous** [comment]
Go ahead 😊 , I've assigned you.
Everyone can contribute to this issue , It'll stay open. 
Just make a pull request with new pages , and i'll merge it if it's relevant 

- Just make sure to add your name in the Readme file too.

**Comment by Neeexxxx** [comment]
Assign it to me Plzz

**Comment by yazdanhaider** [comment]
@TheGuyDangerous please assign me this issue

**Comment by SamagraAg** [comment]
@TheGuyDangerous  can we add any content of our choice(means any receipe) or we have to copy it from somewhere

**Comment by TheGuyDangerous** [comment]
> @TheGuyDangerous can we add any content of our choice(means any receipe) or we have to copy it from somewhere

@SamagraAg Yes , you can add any recipe of your choice , be sure to star ⭐ the repo 😉.

**Comment by ChetnaDiwakar** [comment]
hey, can you please assign me this issue? I'd like to work on it.

**Comment by TheGuyDangerous** [comment]
Go ahead @ChetnaDiwakar !! Happy Hacking 😊 

 • Be sure to star the repo ✨

**Comment by pronajitdey** [comment]
I would like to contribute, please assign it to me

**Comment by TheGuyDangerous** [comment]
Go ahead @pronajitdey :)
Make sure to star the repo while you're at it.

**Comment by TheGuyDangerous** [comment]
For others , you can create new issues to add pages if you want.
I'm closing this issue now
