### ISSUE TITLE
Page titles don't have the site name

### ISSUE THREAD

**Issue by LunarMarathon** [TheGuyDangerous/FoodCoders#26]
![image](https://user-images.githubusercontent.com/113847439/195979065-6e851113-2435-4b85-b8fa-58a685b07e95.png)

All page titles needs to be modified.

**Comment by TheGuyDangerous** [comment]
Go ahead 😊👍

**Comment by NotAtitYet** [comment]
Please assign this to me.

**Comment by TheGuyDangerous** [comment]
@NotAtitYet Not a relevant issue anymore, you can contribute to other issues ✨
