### ISSUE TITLE
I want to add a favicon to the web pages 

### ISSUE THREAD

**Issue by devMuhammad05** [TheGuyDangerous/FoodCoders#33]
I want to add a favicon to the web pages, could you please assign this task to me

**Comment by TheGuyDangerous** [comment]
Go ahead 😊

**Comment by Manish12-verma** [comment]
i want to add favicon to the webpage,please assign this task to me

**Comment by TheGuyDangerous** [comment]
@Manish12-verma Go ahead 😊, I'll merge it for whoever does it first.
 - Make sure to Add favicon to every page in the site.
 -  add the icon in a new folder inside images folder.
 -  Make sure to use relevant icons.

**Comment by devMuhammad05** [comment]
@TheGuyDangerous I have added the favicon please check my PR

**Comment by TheGuyDangerous** [comment]
@Muhammad235 I have attached your contribution 😊.

@Manish12-verma you can add fav icons for the remaining new pages (i.e. Page 5 ,6)

**Comment by atharv-10** [comment]
@TheGuyDangerous I have updated the favicon, can you check please?
