### ISSUE TITLE
Carousel slider 

### ISSUE THREAD

**Issue by UditDe** [TheGuyDangerous/FoodCoders#39]
**Is your feature request related to a problem? Please describe.**
 Adding a slider list so that visitors of your website can see your recipes at a glance.

**Describe the solution you'd like**
We just need to add a carousel slider to the code base

**Comment by UditDe** [comment]
please assing this task to me

**Comment by TheGuyDangerous** [comment]
Go ahead 😊👍
Make sure to star the repo while you're at it.

**Comment by TheGuyDangerous** [comment]
I have merged the Pr , but there is an issue with the Page's responsiveness on other platforms
Kindly look into it .

Rest , the UI Improvements are of the highest quality 🤍
I am Linking a sample screenshot -
![Screenshot_20221016_125910](https://user-images.githubusercontent.com/78858516/196023845-a9a45a31-15c4-436d-93fb-ddbcd64285e2.jpg)

**Comment by UditDe** [comment]
Ok... I will be working on it 🙂

**Comment by tejus0** [comment]
hey @TheGuyDangerous can i work on your slider to make it responsive and beautiful ?

**Comment by TheGuyDangerous** [comment]
sure @tejus0 go ahead 😊
