### ISSUE TITLE
Improved header (Navbar)

### ISSUE THREAD

**Issue by radzhiv25** [TheGuyDangerous/FoodCoders#40]
With Some UI improvements for an enhanced look 
Please consider it under Hacktoberfest.

**Comment by TheGuyDangerous** [comment]
Go ahead, make sure to star the repo while you're at it 😊

**Comment by Rishabhjain2002** [comment]
Is anyone still working on this issue or should I give a try...??

**Comment by TheGuyDangerous** [comment]
@Rishabhjain2002 go ahead and try it , if @radzhiv25 doesn't reply within 24 hours.
Otherwise, there are other issues you can contribute to.
You can also create new issues based on webpage improvements as you like 😊
Make sure to Read the contributing guidelines and star the repo ✨

**Comment by radzhiv25** [comment]
> @Rishabhjain2002 go ahead and try it , if @radzhiv25 doesn't reply within 24 hours. Otherwise, there are other issues you can contribute to. You can also create new issues based on webpage improvements as you like 😊 Make sure to Read the contributing guidelines and star the repo ✨

sorry for the delay will be merged by tomorrow

**Comment by radzhiv25** [comment]
> > @Rishabhjain2002 go ahead and try it , if @radzhiv25 doesn't reply within 24 hours. Otherwise, there are other issues you can contribute to. You can also create new issues based on webpage improvements as you like 😊 Make sure to Read the contributing guidelines and star the repo ✨
> 
> sorry for the delay will be merged by tomorrow

sorry for the delay again 
I am not able to understand the classes made and how to further change the code
You can assign it to someone else
