### ISSUE TITLE
Adding Contact Us Page

### ISSUE THREAD

**Issue by arindam369** [TheGuyDangerous/FoodCoders#50]
I want to add contact us page for this website. Can you attach the hacktoberfest labels and assign me this issue ?

**Comment by TheGuyDangerous** [comment]
Go ahead 😊

**Comment by tejus0** [comment]
Hey @TheGuyDangerous  is this issue available to work on ? I want to make contact page for your website .

**Comment by TheGuyDangerous** [comment]
> Hey @TheGuyDangerous is this issue available to work on ? I want to make contact page for your website .

Hi @tejus0 , no @arindam369 has done a great job so far , there was a mistake was from my end. So I am waiting for him to resubmit his PR.
You Can contribute to , or create new issues as you wish , get them assigned and work on them 😊.
Make sure to star ✨ the repo as it helps us out.

**Comment by TheGuyDangerous** [comment]
@arindam369 refer to #58
