### ISSUE TITLE
Add new page

### ISSUE THREAD

**Issue by prachisharma02** [TheGuyDangerous/FoodCoders#52]
want to add a new page of recipies

**Comment by TheGuyDangerous** [comment]
Go ahead 😊✨
Make sure to star the repo

**Comment by prachisharma02** [comment]
sure😊👍

**Comment by pronajitdey** [comment]
I would like to contribute to this, please assign it to me

**Comment by TheGuyDangerous** [comment]
@pronajitdey you can comment under issue #18 to get yourself assigned , and create a PR accordingly.

**Comment by tanyaa-arora** [comment]
I would like to contribute to the issue

**Comment by TheGuyDangerous** [comment]
go ahead @tanyaa-arora , send your PR

**Comment by tanyaa-arora** [comment]
Can you give me some nore details about the issue

**Comment by tanyaa-arora** [comment]
More*

**Comment by TheGuyDangerous** [comment]
@tanyaa-arora you can refer to #18 to get more information , and create a PR accordingly.
Alternatively, you can also visit contributing.md file to know more.
Happy Hacking !!😉
