### ISSUE TITLE
adding animations in the home page

### ISSUE THREAD

**Issue by Shinchan3102** [TheGuyDangerous/FoodCoders#54]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by Shinchan3102** [comment]
@TheGuyDangerous assign me this task i want to work  on it

**Comment by Shinchan3102** [comment]
please consider it under hactoberfest 2022

**Comment by TheGuyDangerous** [comment]
Alright, go ahead 😊✨
Make sure to star the repo
