### ISSUE TITLE
Will add the login and sign up page in the website and make some responsiveness changes

### ISSUE THREAD

**Issue by MAYANK816** [TheGuyDangerous/FoodCoders#65]
**Describe the solution you'd like**
I will add two pages login and signup pages with clear UI.

**Comment by MAYANK816** [comment]
And Please let me know this repo still participating in hacktoberfest.

**Comment by TheGuyDangerous** [comment]
Yes , the repo is participating in hacktoberfest , and go ahead with with your  ideas💡
Also , star the repo ✨ as it'll help me out 😉
