### ISSUE TITLE
Customized contact page

### ISSUE THREAD

**Issue by ujjawalD07** [TheGuyDangerous/FoodCoders#75]
![pr](https://user-images.githubusercontent.com/87711904/196135229-17215cec-c58d-4842-948d-2c8ebbef6df9.JPG)

### **Made the contact form more attractive using bootstrap. Changed the image adjacent to it, this looks more professional. Kindly assign me this so I can make the PR. Thanks**

**Comment by TheGuyDangerous** [comment]
Go ahead @ujjawalD07 :)🤍

**Comment by ujjawalD07** [comment]
Kindly merge the PR under hacktober-accepted tag @TheGuyDangerous. Thanks:)
