### ISSUE TITLE
Add more recipes

### ISSUE THREAD

**Issue by Wangata** [TheGuyDangerous/FoodCoders#76]
**Is your feature request related to a problem? Please describe.**
No its not related to a problem, its related to an addition to the recipes on the website

**Describe the solution you'd like**
I would like to add more recipes that I enjoy and links on how to prepare them.
**Describe alternatives you've considered**
Add more recipes!
**Additional context**
N/A

**Comment by TheGuyDangerous** [comment]
Go ahead !!

**Comment by azmat-siddiqui** [comment]
Please assign me this issue...

**Comment by TheGuyDangerous** [comment]
Go ahead !! @azmatsiddiqui16
