### ISSUE TITLE
Sir I want to add animations to the footer of about.html

### ISSUE THREAD

**Issue by guptakshitij2308** [TheGuyDangerous/FoodCoders#81]
Respected Sir(@TheGuyDangerous ) Please assign this issue to me under hacktober fest.Thanks!
![image](https://user-images.githubusercontent.com/111740678/196272773-0a21d5ec-ac43-4fef-9265-72f6d8371afc.png)

**Comment by TheGuyDangerous** [comment]
Not required at the moment 😊
You can work on other issues , create a new page and add 6 more recipes
