### ISSUE TITLE
Documentation (Update Read Me)

### ISSUE THREAD

**Issue by Wangata** [TheGuyDangerous/FoodCoders#85]
**Is your feature request related to a problem? Please describe.**
I want to update the ReadMe and make proper documentation on it 
**Describe the solution you'd like**
A step-by-step guide on how a developer can pull a request and push the changes he/she has made 
**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by TheGuyDangerous** [comment]
Contributions.md file fixes this issue

**Comment by Wangata** [comment]
Yeah hadn't checked it out
