### ISSUE TITLE
I want to work on your contact page to enhance it...plz assign this task to me

### ISSUE THREAD

**Issue by aryan-jaiswal-12** [TheGuyDangerous/FoodCoders#88]

**Comment by TheGuyDangerous** [comment]
Attach screenshots of , the kinds of enhancements you are talking about

**Comment by aryan-jaiswal-12** [comment]
![Screenshot 2022-10-18 165103](https://user-images.githubusercontent.com/99496244/196416777-9e8f20e7-8010-493a-a910-f6e6c9cd7984.png)

**Comment by TheGuyDangerous** [comment]
Go ahead !!
 - Make sure it follows the website's theme
 - include github link of the repo under follow us tab
 - remove the "Image from freepik" label
 - Make sure to include the header and footer of the page
 
## Details necessary -
mail - sannidhyadubey@gmail.com
twitter - twitter.com/TheGuyDangerous
insta - instagram.com/sannnidhya

**Comment by azmat-siddiqui** [comment]
Can you assign me this issue??

**Comment by TheGuyDangerous** [comment]
Sure @azmatsiddiqui16 go ahead !
